# Generated by Django 5.1.7 on 2025-04-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_options_alter_expense_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
    ]
