services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: iceplant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iceplantnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iceplant-backend
    working_dir: /app/iceplant_portal
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      DJANGO_CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      DJANGO_DEBUG: "True"
      POSTGRES_DB: iceplant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./iceplant_portal:/app/iceplant_portal
    networks:
      - iceplantnet

  frontend:
    image: node:18-alpine
    container_name: iceplant-frontend
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://backend:8000"
    volumes:
      - ./iceplant_portal/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - iceplantnet

volumes:
  pgdata:

networks:
  iceplantnet:
    driver: bridge
