version: '3.8'

services:
  web:
    build: .
    container_name: iceplant_web
    command: /app/docker-entrypoint.sh
    ports:
      - "8000:8000"
      - "5173:5173"
    env_file:
      - ./.env
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - .:/app
      - static_volume:/app/iceplant_portal/static
      - media_volume:/app/iceplant_portal/media
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: iceplant_db
    environment:
      POSTGRES_DB: iceplantdb
      POSTGRES_USER: iceplantuser
      POSTGRES_PASSWORD: iceplantpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
