version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: iceplant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iceplantnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iceplant-portal
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      POSTGRES_DB: iceplant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    networks:
      - iceplantnet

volumes:
  pgdata:
    driver: local

networks:
  iceplantnet:
    driver: bridge
