version: '3'

services:
  iceplant:
    image: iceplantph/iceplant-portal:latest
    container_name: iceplant-app
    ports:
      - "8080:5173"  # Frontend port
      - "8000:8000"  # Backend port
    volumes:
      - iceplant_data:/app/iceplant_portal/data
      - iceplant_media:/app/iceplant_portal/media
      - iceplant_static:/app/iceplant_portal/staticfiles
    environment:
      - FRONTEND_PORT=5173
      - BACKEND_PORT=8000
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,146.190.201.119,cma.atlantis-fishing.com
    restart: always

volumes:
  iceplant_data:
  iceplant_media:
  iceplant_static:
