# Generated by Django 5.1.7 on 2025-03-31 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('sales_agent', 'Sales Agent'), ('inventory_clerk', 'Inventory Clerk'), ('viewer', 'Viewer'), ('custom', 'Custom Role')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('inventory_view', 'Can view inventory'), ('inventory_add', 'Can add inventory items'), ('inventory_edit', 'Can edit inventory items'), ('inventory_delete', 'Can delete inventory items'), ('sales_view', 'Can view sales'), ('sales_add', 'Can add sales'), ('sales_edit', 'Can edit sales'), ('sales_delete', 'Can delete sales'), ('expenses_view', 'Can view expenses'), ('expenses_add', 'Can add expenses'), ('expenses_edit', 'Can edit expenses'), ('expenses_delete', 'Can delete expenses'), ('expenses_approve', 'Can approve expenses'), ('buyers_view', 'Can view buyers'), ('buyers_add', 'Can add buyers'), ('buyers_edit', 'Can edit buyers'), ('buyers_delete', 'Can delete buyers'), ('attendance_view', 'Can view attendance'), ('attendance_add', 'Can add attendance'), ('attendance_edit', 'Can edit attendance'), ('reports_view', 'Can view reports'), ('reports_export', 'Can export reports'), ('user_management', 'Can manage users'), ('permissions_management', 'Can manage user permissions')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'unique_together': {('user', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('inventory_view', 'Can view inventory'), ('inventory_add', 'Can add inventory items'), ('inventory_edit', 'Can edit inventory items'), ('inventory_delete', 'Can delete inventory items'), ('sales_view', 'Can view sales'), ('sales_add', 'Can add sales'), ('sales_edit', 'Can edit sales'), ('sales_delete', 'Can delete sales'), ('expenses_view', 'Can view expenses'), ('expenses_add', 'Can add expenses'), ('expenses_edit', 'Can edit expenses'), ('expenses_delete', 'Can delete expenses'), ('expenses_approve', 'Can approve expenses'), ('buyers_view', 'Can view buyers'), ('buyers_add', 'Can add buyers'), ('buyers_edit', 'Can edit buyers'), ('buyers_delete', 'Can delete buyers'), ('attendance_view', 'Can view attendance'), ('attendance_add', 'Can add attendance'), ('attendance_edit', 'Can edit attendance'), ('reports_view', 'Can view reports'), ('reports_export', 'Can export reports'), ('user_management', 'Can manage users'), ('permissions_management', 'Can manage user permissions')], max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='user_management.userrole')),
            ],
            options={
                'unique_together': {('role', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='user_management.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
