# Generated by Django 5.1.7 on 2025-03-30 10:13

import companyconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Ice Plant', max_length=200)),
                ('company_address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_state', models.CharField(blank=True, max_length=100, null=True)),
                ('company_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company_country', models.CharField(default='Philippines', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Company Tax ID/VAT Number', max_length=100, null=True)),
                ('business_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('ice_block_weight', models.DecimalField(decimal_places=2, default=100.0, help_text='Default weight of a single ice block in kg', max_digits=6)),
                ('production_capacity', models.IntegerField(default=1000, help_text='Production capacity in blocks per day')),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo for UI and printed documents', null=True, upload_to=companyconfig.models.company_logo_upload_path)),
                ('invoice_footer_text', models.TextField(blank=True, help_text='Text to appear at the bottom of invoices', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
