# Generated by Django 5.1.7 on 2025-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default tax percentage to apply on sales invoices', max_digits=5),
        ),
    ]
