# Generated by Django 5.1.7 on 2025-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyconfig', '0002_companysettings_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tax_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable tax calculation on sales'),
        ),
    ]
