# Generated by Django 5.1.7 on 2025-04-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyconfig', '0003_companysettings_tax_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='tax_enabled',
            field=models.BooleanField(default=False, help_text='Is tax enabled for the company'),
        ),
    ]
