# Generated by Django 5.1.7 on 2025-03-30 05:13

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-sale_time'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='brine_level',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sale',
            name='brine1_identifier',
            field=models.CharField(blank=True, help_text='Identifier for blocks from Brine 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='brine2_identifier',
            field=models.CharField(blank=True, help_text='Identifier for blocks from Brine 2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid in cash', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_quantity',
            field=models.IntegerField(default=0, help_text='Number of blocks delivered'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pickup_quantity',
            field=models.IntegerField(default=0, help_text='Number of blocks picked up'),
        ),
        migrations.AddField(
            model_name='sale',
            name='po_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount covered by Purchase Order', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_per_block',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per ice block', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='si_number',
            field=models.CharField(default='', help_text='Sales Invoice number', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, help_text='Remarks or other notes', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
