# Generated by Django 5.1.7 on 2025-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_remove_sale_brine_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('error', 'Error/Mistake')], default='active', help_text='The current status of the sale record', max_length=10),
        ),
    ]
