# Generated by Django 5.1.7 on 2025-03-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
        ('sales', '0003_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='Reference to buyer record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='buyers.buyer'),
        ),
    ]
