# Generated by Django 5.1.7 on 2025-03-30 09:29

from django.db import migrations


def convert_active_to_processed(apps, schema_editor):
    # Get the historical model
    Sale = apps.get_model('sales', 'Sale')
    # Update all 'active' status records to 'processed'
    Sale.objects.filter(status='active').update(status='processed')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_change_status_active_to_processed'),
    ]

    operations = [
        migrations.RunPython(convert_active_to_processed),
    ]
