# Generated by Django 5.1.7 on 2025-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_convert_active_to_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_iceplant',
            field=models.BooleanField(default=True, help_text='Is this an Iceplant sale?'),
        ),
    ]
