# Generated by Django 5.1.7 on 2025-03-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
