# Generated by Django 5.1.7 on 2025-03-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('shift_start', models.TimeField(help_text='Shift start time (e.g., 06:00 for morning, 18:00 for night)')),
                ('shift_end', models.TimeField(help_text='Shift end time (e.g., 16:00 for morning, 04:00 for night)')),
                ('break_duration', models.IntegerField(default=2, help_text='Break duration in hours')),
                ('is_night_shift', models.BooleanField(default=False, help_text='If True, shift ends next day')),
            ],
        ),
    ]
