# Generated by Django 5.1.7 on 2025-03-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employeeshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='is_rotating_shift',
            field=models.BooleanField(default=False, help_text='If True, employee works rotating shifts'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='rotation_partner_id',
            field=models.CharField(blank=True, help_text='Employee ID of the rotation partner for 12-hour shifts', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='shift_duration',
            field=models.IntegerField(default=8, help_text='Shift duration in hours'),
        ),
    ]
