# Generated by Django 5.1.7 on 2025-03-23 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeeshift_is_rotating_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='import_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee_id'], name='attendance__employe_c89dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['check_in'], name='attendance__check_i_e94952_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['department'], name='attendance__departm_d2ff98_idx'),
        ),
    ]
