# Generated by Django 5.1.7 on 2025-03-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_import_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
