# Generated by Django 5.1.7 on 2025-03-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_create_employee_profiles'),
        ('attendance', '0007_employeeprofile'),
    ]

    operations = [
    ]
