# Generated by Django 5.1.7 on 2025-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_merge_20250323_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department_track_shifts',
            field=models.BooleanField(default=False, help_text='Department-level setting for shift tracking'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='track_shifts',
            field=models.BooleanField(default=False, help_text='Enable shift tracking for this employee'),
        ),
    ]
