# Generated by Django 5.1.7 on 2025-03-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_employeeprofile_department_track_shifts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, unique=True)),
                ('shift_start', models.TimeField(help_text='Default shift start time for the department')),
                ('shift_end', models.TimeField(help_text='Default shift end time for the department')),
                ('break_duration', models.IntegerField(default=2, help_text='Default break duration in hours')),
                ('is_night_shift', models.BooleanField(default=False, help_text='If True, shift ends next day')),
                ('is_rotating_shift', models.BooleanField(default=False, help_text='If True, department uses rotating shifts')),
                ('shift_duration', models.IntegerField(default=8, help_text='Default shift duration in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Shift',
                'verbose_name_plural': 'Department Shifts',
                'ordering': ['department'],
            },
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='department',
            field=models.CharField(blank=True, help_text="Employee's department for shift inheritance", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='use_department_settings',
            field=models.BooleanField(default=True, help_text='If True, use department shift settings'),
        ),
    ]
