# Generated by Django 5.1.7 on 2025-03-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_departmentshift_employeeshift_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentshift',
            options={'ordering': ['department', 'shift_type'], 'verbose_name': 'Department Shift', 'verbose_name_plural': 'Department Shifts'},
        ),
        migrations.RemoveField(
            model_name='departmentshift',
            name='is_night_shift',
        ),
        migrations.AddField(
            model_name='departmentshift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('night', 'Night Shift')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentshift',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
