# Generated by Django 5.1.7 on 2025-03-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_departmentshift_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentshift',
            unique_together={('department', 'shift_type')},
        ),
    ]
