# Generated by Django 5.1.7 on 2025-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_departmentshift_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=10)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('stack', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='attendance__timesta_236462_idx'), models.Index(fields=['source'], name='attendance__source_ee0dd2_idx'), models.Index(fields=['level'], name='attendance__level_5856e5_idx')],
            },
        ),
    ]
