# Generated by Django 5.1.7 on 2025-03-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_systemlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
