# Generated by Django 5.1.7 on 2025-03-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_delete_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration between check_in and check_out', null=True),
        ),
    ]
