# Generated by Django 5.1.7 on 2025-04-01 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_attendance_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['import_date'], 'permissions': [('import_attendance', 'Can import attendance data')], 'verbose_name': 'Import Log', 'verbose_name_plural': 'Import Logs'},
        ),
        migrations.AddField(
            model_name='importlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
