# Generated by Django 5.1.7 on 2025-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_importlog_options_importlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hr_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to HR', null=True),
        ),
    ]
