# Generated by Django 5.1.7 on 2025-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_attendance_hr_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
