# Generated by Django 5.1.7 on 2025-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_attendance_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked',
            field=models.BooleanField(default=False, help_text='Indicates initial processing before HR approval'),
        ),
    ]
