# Generated by Django 5.1.7 on 2025-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_attendanceapprovallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceapprovallog',
            name='shift_end',
            field=models.CharField(blank=True, help_text='Shift end time (HH:MM)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendanceapprovallog',
            name='shift_start',
            field=models.CharField(blank=True, help_text='Shift start time (HH:MM)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendanceapprovallog',
            name='shift_type',
            field=models.CharField(blank=True, help_text='Shift type (Morning, Night, Rotating)', max_length=50, null=True),
        ),
    ]
