# Generated by Django 5.1.7 on 2025-04-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_attendanceapprovallog_shift_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='manual_entry',
            field=models.BooleanField(default=False, help_text='Indicates if check-in or check-out time was manually entered'),
        ),
    ]
