# Generated by Django 5.1.7 on 2025-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_attendance_manual_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_show',
            field=models.BooleanField(default=False, help_text='Indicates employee did not show up for work'),
        ),
    ]
