name: Database Backup

on:
  schedule:
    # Run at 1:00 AM UTC every day
    - cron: '0 1 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run backup script
      run: |
        python manage.py dumpdata > backup_$(date +%Y-%m-%d).json
      
    - name: Upload backup artifact
      uses: actions/upload-artifact@v3
      with:
        name: database-backup-${{ github.run_id }}
        path: backup_*.json
        retention-days: 30 